<?php
/**
 * ProductconfiguratorPropertyType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Product Configurator Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ProductconfiguratorPropertyType Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProductconfiguratorPropertyType
{
    /**
     * Possible values of this enum
     */
    public const UNKNOWN = 'PROPERTY_TYPE_UNKNOWN';

    public const GENERIC = 'PROPERTY_TYPE_GENERIC';

    public const PRICE = 'PROPERTY_TYPE_PRICE';

    public const WEIGHT = 'PROPERTY_TYPE_WEIGHT';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNKNOWN,
            self::GENERIC,
            self::PRICE,
            self::WEIGHT
        ];
    }
}


