<?php
/**
 * ProductConfiguratorApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Product Configurator Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProductConfiguratorApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProductConfiguratorApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for productConfiguratorBulkCreateOptions
     *
     * .
     *
     */
    public function testProductConfiguratorBulkCreateOptions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productConfiguratorBulkCreateProperties
     *
     * .
     *
     */
    public function testProductConfiguratorBulkCreateProperties()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productConfiguratorBulkCreateSteps
     *
     * .
     *
     */
    public function testProductConfiguratorBulkCreateSteps()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productConfiguratorBulkDeleteOptions
     *
     * .
     *
     */
    public function testProductConfiguratorBulkDeleteOptions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productConfiguratorBulkDeleteSteps
     *
     * .
     *
     */
    public function testProductConfiguratorBulkDeleteSteps()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productConfiguratorBulkUpdateOptions
     *
     * .
     *
     */
    public function testProductConfiguratorBulkUpdateOptions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productConfiguratorBulkUpdateProperties
     *
     * .
     *
     */
    public function testProductConfiguratorBulkUpdateProperties()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productConfiguratorCopyConfigurator
     *
     * .
     *
     */
    public function testProductConfiguratorCopyConfigurator()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productConfiguratorCopyOption
     *
     * .
     *
     */
    public function testProductConfiguratorCopyOption()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productConfiguratorCopyStep
     *
     * .
     *
     */
    public function testProductConfiguratorCopyStep()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productConfiguratorCreateDependency
     *
     * .
     *
     */
    public function testProductConfiguratorCreateDependency()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productConfiguratorCreateMatrix
     *
     * .
     *
     */
    public function testProductConfiguratorCreateMatrix()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productConfiguratorCreateOption
     *
     * .
     *
     */
    public function testProductConfiguratorCreateOption()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productConfiguratorCreateProperty
     *
     * .
     *
     */
    public function testProductConfiguratorCreateProperty()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productConfiguratorCreateStep
     *
     * .
     *
     */
    public function testProductConfiguratorCreateStep()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productConfiguratorDeleteConfigurator
     *
     * .
     *
     */
    public function testProductConfiguratorDeleteConfigurator()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productConfiguratorDeleteDependency
     *
     * .
     *
     */
    public function testProductConfiguratorDeleteDependency()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productConfiguratorDeleteMatrix
     *
     * .
     *
     */
    public function testProductConfiguratorDeleteMatrix()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productConfiguratorDeleteOption
     *
     * .
     *
     */
    public function testProductConfiguratorDeleteOption()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productConfiguratorDeleteStep
     *
     * .
     *
     */
    public function testProductConfiguratorDeleteStep()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productConfiguratorGetAvailableConfiguration
     *
     * .
     *
     */
    public function testProductConfiguratorGetAvailableConfiguration()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productConfiguratorGetAvailableConfiguration2
     *
     * .
     *
     */
    public function testProductConfiguratorGetAvailableConfiguration2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productConfiguratorGetConfigurationFromSelections
     *
     * .
     *
     */
    public function testProductConfiguratorGetConfigurationFromSelections()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productConfiguratorGetMatrix
     *
     * .
     *
     */
    public function testProductConfiguratorGetMatrix()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productConfiguratorListDependencies
     *
     * .
     *
     */
    public function testProductConfiguratorListDependencies()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productConfiguratorListMatrices
     *
     * .
     *
     */
    public function testProductConfiguratorListMatrices()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productConfiguratorListOptions
     *
     * .
     *
     */
    public function testProductConfiguratorListOptions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productConfiguratorListProperties
     *
     * .
     *
     */
    public function testProductConfiguratorListProperties()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productConfiguratorRemovePricelistFromMatrix
     *
     * .
     *
     */
    public function testProductConfiguratorRemovePricelistFromMatrix()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productConfiguratorUpdateConfigurator
     *
     * .
     *
     */
    public function testProductConfiguratorUpdateConfigurator()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productConfiguratorUpdateDependency
     *
     * .
     *
     */
    public function testProductConfiguratorUpdateDependency()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productConfiguratorUpdateMatrix
     *
     * .
     *
     */
    public function testProductConfiguratorUpdateMatrix()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productConfiguratorUpdateOption
     *
     * .
     *
     */
    public function testProductConfiguratorUpdateOption()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productConfiguratorUpdateProperty
     *
     * .
     *
     */
    public function testProductConfiguratorUpdateProperty()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productConfiguratorUpdateStep
     *
     * .
     *
     */
    public function testProductConfiguratorUpdateStep()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
